"""Hand-computed regression tests for opportunity_view.py's real-fee PASS
double-check (_real_fee_status / _shape_route).

Motivation, confirmed empirically on live data (2026-08-19): of 6 markets
the flat 0.3% fee_buffer classified PASS, 4 had a real, per-venue-fee-
adjusted profit of exactly $0 -- Kalshi's ~7% taker coefficient and
Polymarket's own posted rate, both nonlinear in price (rate*p*(1-p)), can
each individually exceed the flat buffer. PASS/"ARB FOUND" must require a
real, executable profit, not just "cleared a flat approximation."

Every expected numeric value below was derived independently by hand (shown
in each test's docstring) and cross-checked with a standalone arithmetic
script that does not import this project's code -- never generated by
running the function under test and copying its output.
"""

import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from arb_engine import check_binary_cross_venue_arbs  # noqa: E402
from models import MarketGroup, NormalizedPrice  # noqa: E402
from opportunity_view import _real_fee_status, _shape_route  # noqa: E402

_FEE_BUFFER = 0.003


def make_price(venue, market_id, yes_ask=None, no_ask=None, size=None, taker_fee_rate=None):
    """Minimal NormalizedPrice builder -- mirrors tests/test_slippage.py's
    make_price, fixed placeholders for fields irrelevant to this file's math.
    """
    return NormalizedPrice(
        venue=venue,
        market_id=market_id,
        canonical_market_name="Test Market",
        raw_market_name="Test Market?",
        outcome_name="Yes",
        market_type="binary",
        yes_bid=None,
        yes_ask=yes_ask,
        no_bid=None,
        no_ask=no_ask,
        depth=size,
        volume=None,
        close_time=None,
        resolution_notes=None,
        timestamp="2026-01-01T00:00:00Z",
        yes_ask_size=size,
        no_ask_size=size,
        taker_fee_rate=taker_fee_rate,
    )


class TestRealFeeStatusUnit(unittest.TestCase):
    """Direct tests of _real_fee_status's 4 logical branches, independent of
    any pricing math.
    """

    def test_non_pass_raw_status_always_no_edge(self):
        # Even a suspiciously-positive sizing dict must not resurrect a raw
        # "NO EDGE"/"REVIEW" classification into anything PASS-like --
        # arb_engine's own classification is the first gate, never bypassed.
        sizing = {"estimated_profit_after_fees": 999.0}
        self.assertEqual(_real_fee_status("NO EDGE", sizing), "NO_EDGE")
        self.assertEqual(_real_fee_status("REVIEW", sizing), "NO_EDGE")

    def test_pass_with_positive_real_profit_stays_pass(self):
        sizing = {"estimated_profit_after_fees": 0.01}
        self.assertEqual(_real_fee_status("PASS", sizing), "PASS")

    def test_pass_with_zero_real_profit_downgraded(self):
        sizing = {"estimated_profit_after_fees": 0.0}
        self.assertEqual(_real_fee_status("PASS", sizing), "FEE_ADJUSTED_NO_EDGE")

    def test_pass_with_negative_real_profit_downgraded(self):
        sizing = {"estimated_profit_after_fees": -0.02}
        self.assertEqual(_real_fee_status("PASS", sizing), "FEE_ADJUSTED_NO_EDGE")

    def test_pass_with_unavailable_sizing_downgraded_not_trusted(self):
        # Can't verify real profit -> must not default to trusting the flat
        # buffer's PASS. Erring toward caution, same principle as
        # UNVERIFIED_MATCH never being shown as a trusted PASS.
        self.assertEqual(_real_fee_status("PASS", None), "FEE_ADJUSTED_NO_EDGE")


class TestShapeRouteEndToEnd(unittest.TestCase):
    """Builds real NormalizedPrice/MarketGroup objects and runs them through
    the actual, unmodified arb_engine.check_binary_cross_venue_arbs() plus
    the real opportunity_view._shape_route() -- proving the wiring is
    correct end to end, not just the isolated helper above.
    """

    def test_flat_buffer_pass_erased_by_real_fees(self):
        """Kalshi YES 0.50 (size 100, fee rate 0.07) / Polymarket NO 0.49
        (size 100, fee rate 0.05).

        Flat buffer: total_cost=0.99, gross_edge=0.01, net_edge=0.01-0.003
        =0.007 -> PASS (0.007 > 0, clears default min_edge 0.005).

        Real per-unit fee check at the only available book level:
          yes_marginal_fee = 0.07*0.50*0.50 = 0.0175
          no_marginal_fee  = 0.05*0.49*0.51 = 0.012495
          marginal_unit_cost = 0.50+0.49+0.0175+0.012495 = 1.019995
          + fee_buffer 0.003 = 1.022995 >= guaranteed_payout 1.0
          -> rejected at the very first level -> optimal_units=0,
             estimated_profit=0.0 exactly (independently confirmed via a
             standalone script, not this project's code).

        So the real-fee status must downgrade PASS -> FEE_ADJUSTED_NO_EDGE,
        even though arb_engine's own raw status is (correctly, per its flat
        math) still "PASS" -- arb_engine.py itself is not being changed.
        """
        kalshi = make_price("Kalshi", "K1", yes_ask=0.50, size=100, taker_fee_rate=0.07)
        poly = make_price("Polymarket", "P1", no_ask=0.49, size=100, taker_fee_rate=0.05)
        group = MarketGroup(
            canonical_market_name="Test Market", market_type="binary",
            outcomes=["Yes"], prices=[kalshi, poly], match_confidence=1.0,
        )
        opps = check_binary_cross_venue_arbs(group, _FEE_BUFFER, min_edge=0.005)
        self.assertEqual(len(opps), 1)
        self.assertEqual(opps[0].status, "PASS")  # raw engine math, unchanged

        prices_by_key = {("Kalshi", "K1"): kalshi, ("Polymarket", "P1"): poly}
        route = _shape_route(opps[0], prices_by_key)
        self.assertEqual(route["status"], "FEE_ADJUSTED_NO_EDGE")
        self.assertEqual(route["sizing"]["estimated_profit_after_fees"], 0.0)
        self.assertEqual(route["sizing"]["max_units"], 0.0)

    def test_flat_buffer_pass_survives_real_fees(self):
        """Kalshi YES 0.10 / Polymarket NO 0.85, size 10 both sides.

        Flat buffer: total_cost=0.95, gross_edge=0.05, net_edge=0.047 -> PASS.

        Real per-unit fee check:
          yes_marginal_fee = 0.07*0.10*0.90 = 0.0063
          no_marginal_fee  = 0.05*0.85*0.15 = 0.006375
          marginal_unit_cost = 0.10+0.85+0.0063+0.006375 = 0.962675
          + fee_buffer 0.003 = 0.965675 < 1.0 -> level accepted; both sides'
          size-10 levels exhaust together at 10 units:
            total_cost = 10*0.95 = 9.50
            yes_fees = ceil(0.07*10*0.10*0.90*100 - eps)/100 = 0.07 (rounds
                       up to the cent: raw is $0.063)
            no_fees  = round(0.05*10*0.85*0.15, 5) = 0.06375
            total_fees = 0.13375
            profit = 10*1.0 - 9.50 - 0.13375 - 10*0.003 = 0.33625
          Independently confirmed via a standalone script: due to float64
          representation this rounds to 0.3362 (not 0.3363) at 4dp -- real
          profit is positive either way, so status must stay PASS.
        """
        kalshi = make_price("Kalshi", "K2", yes_ask=0.10, size=10, taker_fee_rate=0.07)
        poly = make_price("Polymarket", "P2", no_ask=0.85, size=10, taker_fee_rate=0.05)
        group = MarketGroup(
            canonical_market_name="Test Market 2", market_type="binary",
            outcomes=["Yes"], prices=[kalshi, poly], match_confidence=1.0,
        )
        opps = check_binary_cross_venue_arbs(group, _FEE_BUFFER, min_edge=0.005)
        self.assertEqual(len(opps), 1)
        self.assertEqual(opps[0].status, "PASS")

        prices_by_key = {("Kalshi", "K2"): kalshi, ("Polymarket", "P2"): poly}
        route = _shape_route(opps[0], prices_by_key)
        self.assertEqual(route["status"], "PASS")
        self.assertAlmostEqual(route["sizing"]["estimated_profit_after_fees"], 0.3362, places=4)
        self.assertEqual(route["sizing"]["max_units"], 10)

    def test_below_default_min_edge_never_reaches_pass(self):
        """Sanity check that a flat-buffer-negative pair is filtered out by
        arb_engine before real-fee logic is ever consulted -- the real-fee
        check only ever narrows PASS, never widens NO_EDGE.
        """
        kalshi = make_price("Kalshi", "K3", yes_ask=0.60, size=100, taker_fee_rate=0.07)
        poly = make_price("Polymarket", "P3", no_ask=0.45, size=100, taker_fee_rate=0.05)
        group = MarketGroup(
            canonical_market_name="Test Market 3", market_type="binary",
            outcomes=["Yes"], prices=[kalshi, poly], match_confidence=1.0,
        )
        # total_cost=1.05 > 1.0 -> negative gross_edge -> below default
        # min_edge (0.005) -> arb_engine drops it entirely.
        opps = check_binary_cross_venue_arbs(group, _FEE_BUFFER, min_edge=0.005)
        self.assertEqual(opps, [])


if __name__ == "__main__":
    unittest.main()
