"""Hand-computed regression tests for slippage.py's order-book-walking and
fee-rounding logic (fee *correctness* itself -- the venue formulas -- is out
of scope here; this targets the slippage/sizing mechanics specifically).

Every expected numeric value below was derived independently by hand and
cross-checked with a standalone arithmetic script that does not import this
project's code -- never generated by running max_profitable_units()/
_taker_fee() and copying their output. That's the whole point: a test that
gets its expected value from the function under test can't catch a bug in
that function.
"""

import math
import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from models import ArbOpportunity, NormalizedPrice  # noqa: E402
from slippage import _leg_levels, _taker_fee, max_profitable_units, opportunity_sizing  # noqa: E402


def make_price(
    venue,
    yes_ask=None, no_ask=None, depth=None,
    yes_ask_size=None, no_ask_size=None,
    yes_ask_book=None, no_ask_book=None,
    taker_fee_rate=None, market_id="TEST-ID",
):
    """Minimal NormalizedPrice builder -- fills in fields irrelevant to
    slippage.py's math with fixed placeholders so each test only has to
    state what it actually varies.
    """
    return NormalizedPrice(
        venue=venue,
        market_id=market_id,
        canonical_market_name="Test Market",
        raw_market_name="Test Market?",
        outcome_name="Yes",
        market_type="binary",
        yes_bid=None,
        yes_ask=yes_ask,
        no_bid=None,
        no_ask=no_ask,
        depth=depth,
        volume=None,
        close_time=None,
        resolution_notes=None,
        timestamp="2026-01-01T00:00:00Z",
        yes_ask_size=yes_ask_size,
        no_ask_size=no_ask_size,
        yes_ask_book=yes_ask_book,
        no_ask_book=no_ask_book,
        taker_fee_rate=taker_fee_rate,
    )


class TestTakerFee(unittest.TestCase):
    def test_kalshi_basic_ceil_to_cent(self):
        # raw = 0.07 * 100 * 0.65 * 0.35 = 1.5925 -> rounds UP to $1.60
        self.assertEqual(_taker_fee("Kalshi", 0.65, 100, 0.07), 1.60)

    def test_kalshi_float64_epsilon_regression(self):
        """0.07*100*0.6*0.4 is exactly $1.68 in real arithmetic. Confirmed
        directly (not assumed): raw*100 is NOT the integer 168.0 in float64,
        so a naive ceil() rounds it up to an unearned extra cent ($1.69).
        The epsilon subtraction in _taker_fee must prevent that.
        """
        raw_cents = 0.07 * 100 * 0.6 * 0.4 * 100
        self.assertNotEqual(raw_cents, 168.0, "float noise didn't reproduce -- test no longer isolates the bug")
        self.assertEqual(math.ceil(raw_cents), 169, "sanity check: naive ceil() really would overcharge")
        self.assertEqual(_taker_fee("Kalshi", 0.6, 100, 0.07), 1.68)

    def test_polymarket_basic_round_to_5dp(self):
        # raw = 0.05 * 50 * 0.20 * 0.80 = 0.4 exactly
        self.assertEqual(_taker_fee("Polymarket", 0.20, 50, 0.05), 0.4)

    def test_polymarket_floors_below_minimum_to_zero_not_to_minimum(self):
        # raw = 0.0001 * 1 * 0.01 * 0.99 = 0.00000099 -> rounds to 0.0 at 5dp,
        # which is below the $0.00001 minimum chargeable fee. Must floor to
        # 0.0, not bump up to the $0.00001 minimum.
        self.assertEqual(_taker_fee("Polymarket", 0.01, 1, 0.0001), 0.0)

    def test_unknown_venue_returns_raw_unrounded(self):
        raw = 0.10 * 10 * 0.5 * 0.5
        self.assertEqual(_taker_fee("SomeOtherVenue", 0.5, 10, 0.10), raw)


class TestLegLevels(unittest.TestCase):
    def test_book_present_returned_as_is(self):
        book = [(0.22, 50), (0.20, 50)]
        price = make_price("Polymarket", yes_ask=0.20, yes_ask_size=999, yes_ask_book=book)
        self.assertEqual(_leg_levels(price, "YES"), book)

    def test_no_book_falls_back_to_flat_ask_and_size(self):
        price = make_price("Kalshi", yes_ask=0.30, yes_ask_size=150)
        self.assertEqual(_leg_levels(price, "YES"), [(0.30, 150)])

    def test_no_book_no_size_falls_back_to_depth(self):
        price = make_price("Kalshi", yes_ask=0.30, depth=75.0)
        self.assertEqual(_leg_levels(price, "YES"), [(0.30, 75.0)])

    def test_nothing_available_returns_empty(self):
        price = make_price("Kalshi", yes_ask=None)
        self.assertEqual(_leg_levels(price, "YES"), [])

    def test_zero_size_flat_level_is_not_a_phantom_level(self):
        price = make_price("Kalshi", yes_ask=0.30, yes_ask_size=0)
        self.assertEqual(_leg_levels(price, "YES"), [])

    def test_price_present_but_no_size_or_depth_returns_empty(self):
        price = make_price("Kalshi", yes_ask=0.30)  # no yes_ask_size, no depth
        self.assertEqual(_leg_levels(price, "YES"), [])

    def test_no_side_reads_no_fields_not_yes_fields(self):
        price = make_price("Kalshi", yes_ask=0.30, yes_ask_size=100, no_ask=0.65, no_ask_size=200)
        self.assertEqual(_leg_levels(price, "NO"), [(0.65, 200)])


class TestMaxProfitableUnits(unittest.TestCase):
    def test_single_flat_level_both_sides(self):
        """Both legs are a single flat top-of-book level (Kalshi-style).
        Hand computation:
          yes_fee_rate = 0.07*0.30*0.70 = 0.0147, no_fee_rate = 0.07*0.65*0.35 = 0.015925
          marginal_unit_cost = 0.30+0.65+0.0147+0.015925 = 0.980625 (+0.003 buffer = 0.983625 < 1.0 -> accept)
          yes_fee = ceil(1.47c)=$1.47, no_fee = ceil(159.25c)=$1.60 (rounds up)
          total_cost = 100*0.95 = $95.00, total_fees = $3.07
          profit = 100*1.0 - 95.00 - 3.07 - 100*0.003 = $1.63
        """
        yes = make_price("Kalshi", yes_ask=0.30, yes_ask_size=100, taker_fee_rate=0.07)
        no = make_price("Kalshi", no_ask=0.65, no_ask_size=100, taker_fee_rate=0.07)
        result = max_profitable_units(yes, no, guaranteed_payout=1.0, fee_buffer=0.003)

        self.assertEqual(result["optimal_units"], 100)
        self.assertAlmostEqual(result["total_cost"], 95.0)
        self.assertEqual(result["yes_fees"], 1.47)
        self.assertEqual(result["no_fees"], 1.60)
        self.assertAlmostEqual(result["total_fees"], 3.07)
        self.assertAlmostEqual(result["avg_cost_per_unit"], 0.9807)
        self.assertAlmostEqual(result["estimated_profit"], 1.63)
        self.assertEqual(result["limiting_factor"], "both legs' visible liquidity exhausted")
        self.assertTrue(result["fee_rate_is_estimate"])  # both legs Kalshi

    def test_multilevel_book_partial_exhaustion_and_sorting(self):
        """YES is a 2-level Polymarket book given deliberately UNSORTED (mirrors
        the documented "CLOB levels aren't guaranteed sorted" gotcha) walked
        against a flat Kalshi NO. Hand computation (see module docstring for
        the standalone verification):
          level 1 (0.20, size 50): accept, step=50, yes_fee=$0.40, no_fee=$0.66
          level 2 (0.22, size 50): accept, step=50, yes_fee=$0.429, no_fee=$0.66
          totals: units=100, cost=$96.00, fees=$0.829+$1.32=$2.149, profit=$1.551
        YES's book (50 shares) is smaller than NO's flat size (200) so YES
        runs out first -- must name Polymarket specifically, not "both".
        """
        yes = make_price("Polymarket", yes_ask_book=[(0.22, 50), (0.20, 50)], taker_fee_rate=0.05)
        no = make_price("Kalshi", no_ask=0.75, no_ask_size=200, taker_fee_rate=0.07)
        result = max_profitable_units(yes, no, guaranteed_payout=1.0, fee_buffer=0.003)

        self.assertEqual(result["optimal_units"], 100)
        self.assertAlmostEqual(result["total_cost"], 96.0)
        self.assertAlmostEqual(result["yes_fees"], 0.829)
        self.assertAlmostEqual(result["no_fees"], 1.32)
        self.assertAlmostEqual(result["total_fees"], 2.149)
        self.assertAlmostEqual(result["avg_cost_per_unit"], 0.98149)
        self.assertAlmostEqual(result["estimated_profit"], 1.551)
        self.assertEqual(result["limiting_factor"], "Polymarket YES-side visible liquidity exhausted")

    def test_stopping_condition_excludes_unprofitable_level_entirely(self):
        """A 2nd, deeper book level whose OWN marginal economics are
        unprofitable must be excluded completely -- not partially filled,
        and its size must not count toward "liquidity exhausted" (there's
        1000 more visible on both sides, unused -- the walk stopped on
        economics, not on running out of quotes).
          level 1 (0.40, size 10): marginal_cost+buffer = 0.9325 < 1.0 -> accept, step=10
          level 2 (0.55, size 1000): marginal_cost+buffer = 1.082875 >= 1.0 -> reject, loop breaks
          totals: units=10 (not 1010), cost=$9.00, fees=$0.12+$0.18=$0.30, profit=$0.67
        """
        yes = make_price("Polymarket", yes_ask_book=[(0.40, 10), (0.55, 1000)], taker_fee_rate=0.05)
        no = make_price("Kalshi", no_ask=0.50, no_ask_size=1000, taker_fee_rate=0.07)
        result = max_profitable_units(yes, no, guaranteed_payout=1.0, fee_buffer=0.003)

        self.assertEqual(result["optimal_units"], 10)
        self.assertAlmostEqual(result["total_cost"], 9.0)
        self.assertAlmostEqual(result["yes_fees"], 0.12)
        self.assertAlmostEqual(result["no_fees"], 0.18)
        self.assertAlmostEqual(result["total_fees"], 0.30)
        self.assertAlmostEqual(result["avg_cost_per_unit"], 0.93)
        self.assertAlmostEqual(result["estimated_profit"], 0.67)
        self.assertEqual(
            result["limiting_factor"],
            "slippage crossed breakeven before either leg's visible liquidity ran out",
        )

    def test_accept_reject_uses_unrounded_marginal_rate_not_rounded_step_fee(self):
        """Regression test for the historical stopping-condition bug: the
        accept/reject decision must use the TRUE unrounded marginal fee rate,
        not the rounded fee for whatever tiny size happens to be at the top
        of book.

        Constructed so the two disagree: YES has only 1 share available.
          TRUE unrounded marginal cost = 0.50+0.48+0.0175+0.0 = 0.9975 < 1.0 -> should accept.
          NAIVE (wrong) approach -- using this step's ROUNDED fee as if it
          were the per-unit rate -- would compute 0.50+0.48+$0.02+$0.00 =
          exactly 1.00, which is NOT < 1.0, and would wrongly reject the
          entire level (0 units instead of 1).
        The real code must side with the TRUE economics: 1 unit filled,
        landing at exactly breakeven ($0.00 profit) once the real rounded
        fee is actually charged -- correct and not a loss, whereas the naive
        approach would leave a genuine (if tiny) edge on the table entirely.
        """
        yes = make_price("Kalshi", yes_ask=0.50, yes_ask_size=1, taker_fee_rate=0.07)
        no = make_price("Kalshi", no_ask=0.48, no_ask_size=1000, taker_fee_rate=0.0)
        result = max_profitable_units(yes, no, guaranteed_payout=1.0, fee_buffer=0.0)

        self.assertEqual(result["optimal_units"], 1)
        self.assertAlmostEqual(result["total_cost"], 0.98)
        self.assertEqual(result["yes_fees"], 0.02)
        self.assertEqual(result["no_fees"], 0.0)
        self.assertAlmostEqual(result["estimated_profit"], 0.0, places=9)

    def test_zero_size_level_skipped_without_phantom_units(self):
        """A book whose first level has size 0 (shouldn't normally happen,
        but the code shouldn't produce phantom units or infinite-loop if it
        does) must contribute nothing and cleanly advance to the next level.
          level 1 (0.10, size 0): accept on price, step=0 -> contributes nothing
          level 2 (0.20, size 50): accept, step=50
          totals: units=50 (not 0, not double-counted), cost=$45.00, profit=$3.71
        """
        yes = make_price("Polymarket", yes_ask_book=[(0.10, 0), (0.20, 50)], taker_fee_rate=0.05)
        no = make_price("Kalshi", no_ask=0.70, no_ask_size=50, taker_fee_rate=0.07)
        result = max_profitable_units(yes, no, guaranteed_payout=1.0, fee_buffer=0.003)

        self.assertEqual(result["optimal_units"], 50)
        self.assertAlmostEqual(result["total_cost"], 45.0)
        self.assertAlmostEqual(result["yes_fees"], 0.4)
        self.assertAlmostEqual(result["no_fees"], 0.74)
        self.assertAlmostEqual(result["estimated_profit"], 3.71)
        self.assertEqual(result["limiting_factor"], "both legs' visible liquidity exhausted")

    def test_immediately_unprofitable_first_level_yields_zero_units(self):
        """Regression test: this case (0 units, first level already
        unprofitable) and genuine slippage erosion (>=1 level walked, THEN
        a deeper level rejected -- see
        test_stopping_condition_excludes_unprofitable_level_entirely) used
        to share the same "slippage crossed breakeven..." message. That's
        wrong for THIS case specifically: 0.60+0.60=1.20 already exceeds
        the 1.0 guaranteed payout before a single share is walked, so
        nothing here is a liquidity or slippage story -- the route was
        never profitable at any size. See test_slippage_vs_never_profitable_
        limiting_factor_are_distinct_messages below for the two cases
        verified side by side.
        """
        yes = make_price("Kalshi", yes_ask=0.60, yes_ask_size=100, taker_fee_rate=0.07)
        no = make_price("Kalshi", no_ask=0.60, no_ask_size=100, taker_fee_rate=0.07)
        result = max_profitable_units(yes, no, guaranteed_payout=1.0, fee_buffer=0.003)

        self.assertEqual(result["optimal_units"], 0.0)
        self.assertIsNone(result["avg_cost_per_unit"])
        self.assertEqual(result["yes_fees"], 0.0)
        self.assertEqual(result["no_fees"], 0.0)
        self.assertEqual(result["estimated_profit"], 0.0)
        self.assertEqual(
            result["limiting_factor"],
            "not profitable at any size -- best available price on both legs is already at or past breakeven",
        )

    def test_slippage_vs_never_profitable_limiting_factor_are_distinct_messages(self):
        """Same 2-level Polymarket-vs-Kalshi shape as
        test_stopping_condition_excludes_unprofitable_level_entirely
        (level 1 profitable, level 2 rejected), contrasted directly against
        a version where even level 1 is unprofitable -- confirming the two
        situations never collide on the same message, and specifically
        that walking >=1 level first is what earns the "slippage" wording.
        """
        yes_profitable_first = make_price(
            "Polymarket", yes_ask_book=[(0.40, 10), (0.55, 1000)], taker_fee_rate=0.05
        )
        no_side = make_price("Kalshi", no_ask=0.50, no_ask_size=1000, taker_fee_rate=0.07)
        walked_some = max_profitable_units(yes_profitable_first, no_side, guaranteed_payout=1.0, fee_buffer=0.003)
        self.assertEqual(walked_some["optimal_units"], 10)
        self.assertEqual(
            walked_some["limiting_factor"],
            "slippage crossed breakeven before either leg's visible liquidity ran out",
        )

        # Raise level 1's own price so even the very first unit -- 0.70 +
        # 0.50 = 1.20 -- already exceeds the 1.0 guaranteed payout.
        yes_never_profitable = make_price(
            "Polymarket", yes_ask_book=[(0.70, 10), (0.55, 1000)], taker_fee_rate=0.05
        )
        walked_none = max_profitable_units(yes_never_profitable, no_side, guaranteed_payout=1.0, fee_buffer=0.003)
        self.assertEqual(walked_none["optimal_units"], 0.0)
        self.assertEqual(
            walked_none["limiting_factor"],
            "not profitable at any size -- best available price on both legs is already at or past breakeven",
        )

    def test_no_liquidity_data_returns_empty_result(self):
        yes = make_price("Kalshi", yes_ask=0.30, taker_fee_rate=0.07)  # no size, no depth, no book
        no = make_price("Kalshi", no_ask=0.65, no_ask_size=100, taker_fee_rate=0.07)
        result = max_profitable_units(yes, no, guaranteed_payout=1.0, fee_buffer=0.003)

        self.assertEqual(result["optimal_units"], 0.0)
        self.assertEqual(result["limiting_factor"], "no liquidity/size data available for one or both legs")

    def test_missing_fee_rate_returns_distinct_message(self):
        yes = make_price("Kalshi", yes_ask=0.30, yes_ask_size=100, taker_fee_rate=None)
        no = make_price("Kalshi", no_ask=0.65, no_ask_size=100, taker_fee_rate=0.07)
        result = max_profitable_units(yes, no, guaranteed_payout=1.0, fee_buffer=0.003)

        self.assertEqual(result["optimal_units"], 0.0)
        self.assertEqual(result["limiting_factor"], "no fee rate available for one or both legs")


class TestOpportunitySizing(unittest.TestCase):
    """Wrapper-level tests: leg lookup, key matching, None-handling. Reuses
    the single-flat-level scenario's numbers as a sanity check that it
    delegates correctly, without re-deriving them.
    """

    def _make_leg(self, side, venue, market_id, price):
        return {"action": "BUY", "side": side, "venue": venue, "outcome": "Yes", "price": price, "market_id": market_id}

    def _make_opportunity(self, legs):
        return ArbOpportunity(
            market_name="Test Market", outcome_name="Yes", arb_type="binary", legs=legs,
            total_cost=0.95, guaranteed_payout=1.0, gross_edge=0.05, fee_buffer=0.003,
            net_edge=0.047, estimated_depth=100.0, match_confidence=1.0, status="PASS",
        )

    def test_happy_path_delegates_to_max_profitable_units(self):
        yes_price = make_price("Kalshi", market_id="YES-ID", yes_ask=0.30, yes_ask_size=100, taker_fee_rate=0.07)
        no_price = make_price("Kalshi", market_id="NO-ID", no_ask=0.65, no_ask_size=100, taker_fee_rate=0.07)
        prices_by_key = {("Kalshi", "YES-ID"): yes_price, ("Kalshi", "NO-ID"): no_price}
        opp = self._make_opportunity([
            self._make_leg("YES", "Kalshi", "YES-ID", 0.30),
            self._make_leg("NO", "Kalshi", "NO-ID", 0.65),
        ])

        result = opportunity_sizing(opp, prices_by_key)

        self.assertIsNotNone(result)
        self.assertEqual(result["optimal_units"], 100)
        self.assertAlmostEqual(result["estimated_profit"], 1.63)

    def test_missing_source_row_returns_none(self):
        yes_price = make_price("Kalshi", market_id="YES-ID", yes_ask=0.30, yes_ask_size=100, taker_fee_rate=0.07)
        prices_by_key = {("Kalshi", "YES-ID"): yes_price}  # NO leg's row is missing
        opp = self._make_opportunity([
            self._make_leg("YES", "Kalshi", "YES-ID", 0.30),
            self._make_leg("NO", "Kalshi", "NO-ID", 0.65),
        ])
        self.assertIsNone(opportunity_sizing(opp, prices_by_key))

    def test_non_binary_leg_count_returns_none(self):
        opp = self._make_opportunity([
            self._make_leg("YES", "Kalshi", "A", 0.10),
            self._make_leg("YES", "Polymarket", "B", 0.12),
            self._make_leg("YES", "Kalshi", "C", 0.15),
        ])
        self.assertIsNone(opportunity_sizing(opp, {}))

    def test_two_legs_same_side_returns_none(self):
        opp = self._make_opportunity([
            self._make_leg("YES", "Kalshi", "A", 0.30),
            self._make_leg("YES", "Polymarket", "B", 0.30),
        ])
        self.assertIsNone(opportunity_sizing(opp, {}))


if __name__ == "__main__":
    unittest.main()
