"""Hand-computed regression tests for opportunity_view.py's real-fee PASS
double-check (_real_fee_status / _shape_route).

Motivation, confirmed empirically on live data (2026-08-19): of 6 markets
the flat 0.3% fee_buffer classified PASS, 4 had a real, per-venue-fee-
adjusted profit of exactly $0 -- Kalshi's ~7% taker coefficient and
Polymarket's own posted rate, both nonlinear in price (rate*p*(1-p)), can
each individually exceed the flat buffer. PASS/"ARB FOUND" must require a
real, executable profit, not just "cleared a flat approximation."

Every expected numeric value below was derived independently by hand (shown
in each test's docstring) and cross-checked with a standalone arithmetic
script that does not import this project's code -- never generated by
running the function under test and copying its output.
"""

import sys
import threading
import time
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

import opportunity_view  # noqa: E402
from arb_engine import check_binary_cross_venue_arbs  # noqa: E402
from models import MarketGroup, NormalizedPrice  # noqa: E402
from opportunity_view import _STATUS_RANK, _real_fee_status, _score_candidate, _shape_route  # noqa: E402

_FEE_BUFFER = 0.003


def make_price(venue, market_id, yes_ask=None, no_ask=None, size=None, taker_fee_rate=None):
    """Minimal NormalizedPrice builder -- mirrors tests/test_slippage.py's
    make_price, fixed placeholders for fields irrelevant to this file's math.
    """
    return NormalizedPrice(
        venue=venue,
        market_id=market_id,
        canonical_market_name="Test Market",
        raw_market_name="Test Market?",
        outcome_name="Yes",
        market_type="binary",
        yes_bid=None,
        yes_ask=yes_ask,
        no_bid=None,
        no_ask=no_ask,
        depth=size,
        volume=None,
        close_time=None,
        resolution_notes=None,
        timestamp="2026-01-01T00:00:00Z",
        yes_ask_size=size,
        no_ask_size=size,
        taker_fee_rate=taker_fee_rate,
    )


class TestRealFeeStatusUnit(unittest.TestCase):
    """Direct tests of _real_fee_status's 4 logical branches, independent of
    any pricing math.
    """

    def test_non_pass_raw_status_always_no_edge(self):
        # Even a suspiciously-positive sizing dict must not resurrect a raw
        # "NO EDGE"/"REVIEW" classification into anything PASS-like --
        # arb_engine's own classification is the first gate, never bypassed.
        sizing = {"estimated_profit_after_fees": 999.0}
        self.assertEqual(_real_fee_status("NO EDGE", sizing), "NO_EDGE")
        self.assertEqual(_real_fee_status("REVIEW", sizing), "NO_EDGE")

    def test_pass_with_positive_real_profit_stays_pass(self):
        sizing = {"estimated_profit_after_fees": 0.01}
        self.assertEqual(_real_fee_status("PASS", sizing), "PASS")

    def test_pass_with_zero_real_profit_downgraded(self):
        sizing = {"estimated_profit_after_fees": 0.0}
        self.assertEqual(_real_fee_status("PASS", sizing), "FEE_ADJUSTED_NO_EDGE")

    def test_pass_with_negative_real_profit_downgraded(self):
        sizing = {"estimated_profit_after_fees": -0.02}
        self.assertEqual(_real_fee_status("PASS", sizing), "FEE_ADJUSTED_NO_EDGE")

    def test_pass_with_unavailable_sizing_downgraded_not_trusted(self):
        # Can't compute real profit -> must not default to trusting the
        # flat buffer's PASS. Erring toward caution when the real number
        # simply isn't available, not just when it's confirmed negative.
        self.assertEqual(_real_fee_status("PASS", None), "FEE_ADJUSTED_NO_EDGE")


class TestShapeRouteEndToEnd(unittest.TestCase):
    """Builds real NormalizedPrice/MarketGroup objects and runs them through
    the actual, unmodified arb_engine.check_binary_cross_venue_arbs() plus
    the real opportunity_view._shape_route() -- proving the wiring is
    correct end to end, not just the isolated helper above.
    """

    def test_flat_buffer_pass_erased_by_real_fees(self):
        """Kalshi YES 0.50 (size 100, fee rate 0.07) / Polymarket NO 0.49
        (size 100, fee rate 0.05).

        Flat buffer: total_cost=0.99, gross_edge=0.01, net_edge=0.01-0.003
        =0.007 -> PASS (0.007 > 0, clears default min_edge 0.005).

        Real per-unit fee check at the only available book level:
          yes_marginal_fee = 0.07*0.50*0.50 = 0.0175
          no_marginal_fee  = 0.05*0.49*0.51 = 0.012495
          marginal_unit_cost = 0.50+0.49+0.0175+0.012495 = 1.019995
          + fee_buffer 0.003 = 1.022995 >= guaranteed_payout 1.0
          -> rejected at the very first level -> optimal_units=0,
             estimated_profit=0.0 exactly (independently confirmed via a
             standalone script, not this project's code).

        So the real-fee status must downgrade PASS -> FEE_ADJUSTED_NO_EDGE,
        even though arb_engine's own raw status is (correctly, per its flat
        math) still "PASS" -- arb_engine.py itself is not being changed.
        """
        kalshi = make_price("Kalshi", "K1", yes_ask=0.50, size=100, taker_fee_rate=0.07)
        poly = make_price("Polymarket", "P1", no_ask=0.49, size=100, taker_fee_rate=0.05)
        group = MarketGroup(
            canonical_market_name="Test Market", market_type="binary",
            outcomes=["Yes"], prices=[kalshi, poly], match_confidence=1.0,
        )
        opps = check_binary_cross_venue_arbs(group, _FEE_BUFFER, min_edge=0.005)
        self.assertEqual(len(opps), 1)
        self.assertEqual(opps[0].status, "PASS")  # raw engine math, unchanged

        prices_by_key = {("Kalshi", "K1"): kalshi, ("Polymarket", "P1"): poly}
        route = _shape_route(opps[0], prices_by_key)
        self.assertEqual(route["status"], "FEE_ADJUSTED_NO_EDGE")
        self.assertEqual(route["sizing"]["estimated_profit_after_fees"], 0.0)
        self.assertEqual(route["sizing"]["max_units"], 0.0)

    def test_flat_buffer_pass_survives_real_fees(self):
        """Kalshi YES 0.10 / Polymarket NO 0.85, size 10 both sides.

        Flat buffer: total_cost=0.95, gross_edge=0.05, net_edge=0.047 -> PASS.

        Real per-unit fee check:
          yes_marginal_fee = 0.07*0.10*0.90 = 0.0063
          no_marginal_fee  = 0.05*0.85*0.15 = 0.006375
          marginal_unit_cost = 0.10+0.85+0.0063+0.006375 = 0.962675
          + fee_buffer 0.003 = 0.965675 < 1.0 -> level accepted; both sides'
          size-10 levels exhaust together at 10 units:
            total_cost = 10*0.95 = 9.50
            yes_fees = ceil(0.07*10*0.10*0.90*100 - eps)/100 = 0.07 (rounds
                       up to the cent: raw is $0.063)
            no_fees  = round(0.05*10*0.85*0.15, 5) = 0.06375
            total_fees = 0.13375
            profit = 10*1.0 - 9.50 - 0.13375 - 10*0.003 = 0.33625
          Independently confirmed via a standalone script: due to float64
          representation this rounds to 0.3362 (not 0.3363) at 4dp -- real
          profit is positive either way, so status must stay PASS.
        """
        kalshi = make_price("Kalshi", "K2", yes_ask=0.10, size=10, taker_fee_rate=0.07)
        poly = make_price("Polymarket", "P2", no_ask=0.85, size=10, taker_fee_rate=0.05)
        group = MarketGroup(
            canonical_market_name="Test Market 2", market_type="binary",
            outcomes=["Yes"], prices=[kalshi, poly], match_confidence=1.0,
        )
        opps = check_binary_cross_venue_arbs(group, _FEE_BUFFER, min_edge=0.005)
        self.assertEqual(len(opps), 1)
        self.assertEqual(opps[0].status, "PASS")

        prices_by_key = {("Kalshi", "K2"): kalshi, ("Polymarket", "P2"): poly}
        route = _shape_route(opps[0], prices_by_key)
        self.assertEqual(route["status"], "PASS")
        self.assertAlmostEqual(route["sizing"]["estimated_profit_after_fees"], 0.3362, places=4)
        self.assertEqual(route["sizing"]["max_units"], 10)

    def test_below_default_min_edge_never_reaches_pass(self):
        """Sanity check that a flat-buffer-negative pair is filtered out by
        arb_engine before real-fee logic is ever consulted -- the real-fee
        check only ever narrows PASS, never widens NO_EDGE.
        """
        kalshi = make_price("Kalshi", "K3", yes_ask=0.60, size=100, taker_fee_rate=0.07)
        poly = make_price("Polymarket", "P3", no_ask=0.45, size=100, taker_fee_rate=0.05)
        group = MarketGroup(
            canonical_market_name="Test Market 3", market_type="binary",
            outcomes=["Yes"], prices=[kalshi, poly], match_confidence=1.0,
        )
        # total_cost=1.05 > 1.0 -> negative gross_edge -> below default
        # min_edge (0.005) -> arb_engine drops it entirely.
        opps = check_binary_cross_venue_arbs(group, _FEE_BUFFER, min_edge=0.005)
        self.assertEqual(opps, [])


class TestScanCandidateBestStatus(unittest.TestCase):
    """A scan candidate's best_status picks the best of its routes' real
    statuses (PASS > FEE_ADJUSTED_NO_EDGE > NO_EDGE, via _STATUS_RANK) --
    the exact same selection build_scan_result() already used for
    crosswalk markets, now reused for scan candidates too (there is no
    separate UNVERIFIED_* status anymore; scan candidates use the same
    vocabulary as everything else on the site).
    """

    def test_pass_route_wins_over_no_edge_route_from_same_candidate(self):
        """Kalshi/Polymarket both quote YES and NO, so _score_candidate
        produces 2 routes:
          Route A (buy YES Kalshi 0.10 / NO Polymarket 0.85): total_cost=
          0.95, same numbers as test_flat_buffer_pass_survives_real_fees
          above -- confirmed PASS with real profit ~0.336.
          Route B (buy YES Polymarket 0.90 / NO Kalshi 0.95): total_cost=
          1.85, wildly unprofitable -> raw "NO EDGE" -> shaped "NO_EDGE".
        best_status must be "PASS" (rank 0), not "NO_EDGE" (rank 2) --
        one good route is enough to call the whole candidate profitable.
        """
        kalshi = make_price(
            "Kalshi", "K4", yes_ask=0.10, no_ask=0.95, size=10, taker_fee_rate=0.07
        )
        poly = make_price(
            "Polymarket", "P4", yes_ask=0.90, no_ask=0.85, size=10, taker_fee_rate=0.05
        )

        opps = _score_candidate(kalshi, poly)
        self.assertEqual(len(opps), 2)

        prices_by_key = {("Kalshi", "K4"): kalshi, ("Polymarket", "P4"): poly}
        routes = [_shape_route(opp, prices_by_key) for opp in opps]
        statuses = {r["status"] for r in routes}
        self.assertEqual(statuses, {"PASS", "NO_EDGE"})

        best_status = min((r["status"] for r in routes), key=lambda s: _STATUS_RANK[s])
        self.assertEqual(best_status, "PASS")


class TestScanResultCaching(unittest.TestCase):
    """build_category_scan_result() must be a thin cache wrapper around
    _build_category_scan_result_uncached() -- confirms a repeated call for
    the same category within the TTL never re-hits Kalshi/Polymarket, which
    is what actually caps the worst case for a public, unauthenticated POST
    endpoint (see build_category_scan_result's own comment for why this is
    a real stability requirement, not just a latency optimization).
    """

    def setUp(self):
        # The cache is a module-level singleton (by design -- it must be
        # shared across requests, not per-call) -- clear it before each
        # test so tests can't see each other's cached entries.
        opportunity_view._scan_result_cache._store.clear()

    def test_second_call_same_category_does_not_recompute(self):
        with mock.patch.object(
            opportunity_view, "_build_category_scan_result_uncached", return_value={"category": "tech"}
        ) as mocked:
            first = opportunity_view.build_category_scan_result("tech")
            second = opportunity_view.build_category_scan_result("tech")

        self.assertEqual(first, {"category": "tech"})
        self.assertEqual(second, {"category": "tech"})
        mocked.assert_called_once_with("tech")

    def test_different_categories_computed_independently(self):
        with mock.patch.object(
            opportunity_view,
            "_build_category_scan_result_uncached",
            side_effect=lambda cat: {"category": cat},
        ) as mocked:
            tech_result = opportunity_view.build_category_scan_result("tech")
            sports_result = opportunity_view.build_category_scan_result("sports")

        self.assertEqual(tech_result, {"category": "tech"})
        self.assertEqual(sports_result, {"category": "sports"})
        self.assertEqual(mocked.call_count, 2)


class TestScanSlotSerialization(unittest.TestCase):
    """_build_category_scan_result_uncached() must serialize the actual
    heavy work GLOBALLY across categories, not just per-category like
    _scan_result_cache does. Confirmed as a real cause of an OOM crash on
    the live 512MB deployment, not a hypothetical one (2026-08-20): two
    different categories scanning at once each ran this whole fetch+match+
    price pipeline in their own thread (FastAPI runs this sync route in a
    threadpool), so their peak memory added together instead of one
    waiting for the other.
    """

    def setUp(self):
        opportunity_view._scan_result_cache._store.clear()

    def tearDown(self):
        # Defensive: a failed assertion mid-test could leave the
        # module-level lock held, which would hang every test after it
        # waiting on a lock nobody releases.
        if opportunity_view._scan_slot.locked():
            opportunity_view._scan_slot.release()

    def test_two_categories_never_run_the_heavy_work_at_the_same_time(self):
        concurrent_count = 0
        max_concurrent = 0
        count_lock = threading.Lock()

        def slow_impl(category):
            nonlocal concurrent_count, max_concurrent
            with count_lock:
                concurrent_count += 1
                max_concurrent = max(max_concurrent, concurrent_count)
            time.sleep(0.05)
            with count_lock:
                concurrent_count -= 1
            return {"category": category}

        results = {}

        def worker(cat):
            results[cat] = opportunity_view._build_category_scan_result_uncached(cat)

        with mock.patch.object(opportunity_view, "_scan_category_impl", side_effect=slow_impl):
            t1 = threading.Thread(target=worker, args=("tech",))
            t2 = threading.Thread(target=worker, args=("sports",))
            t1.start()
            t2.start()
            t1.join()
            t2.join()

        self.assertEqual(results, {"tech": {"category": "tech"}, "sports": {"category": "sports"}})
        # The real bug this catches: without the lock, both threads' slow_impl
        # calls would overlap and max_concurrent would hit 2.
        self.assertEqual(max_concurrent, 1)

    def test_second_scan_gives_up_with_busy_error_if_first_is_still_running(self):
        # Hold the slot ourselves to simulate a scan already in progress,
        # with a short timeout override so this test doesn't take the real
        # 30s production value.
        opportunity_view._scan_slot.acquire()
        try:
            with mock.patch.object(opportunity_view, "_SCAN_SLOT_TIMEOUT_SECONDS", 0.05):
                with self.assertRaises(opportunity_view.ScanBusyError):
                    opportunity_view._build_category_scan_result_uncached("tech")
        finally:
            opportunity_view._scan_slot.release()

    def test_slot_is_released_after_a_normal_scan_so_the_next_one_can_run(self):
        with mock.patch.object(
            opportunity_view, "_scan_category_impl", side_effect=lambda cat: {"category": cat}
        ):
            opportunity_view._build_category_scan_result_uncached("tech")
            # If the slot weren't released, this second call would block for
            # the full timeout and raise ScanBusyError instead of returning.
            result = opportunity_view._build_category_scan_result_uncached("sports")

        self.assertEqual(result, {"category": "sports"})

    def test_slot_is_released_even_if_the_scan_raises(self):
        with mock.patch.object(opportunity_view, "_scan_category_impl", side_effect=RuntimeError("boom")):
            with self.assertRaises(RuntimeError):
                opportunity_view._build_category_scan_result_uncached("tech")

        self.assertFalse(opportunity_view._scan_slot.locked())


if __name__ == "__main__":
    unittest.main()
